pub const META_POCKETCASTS_PODCAST_UUID: &str = "POCKETCASTS_PODCAST_UUID";
pub const META_POCKETCASTS_STREAM_URL: &str = "POCKETCASTS_STREAM_URL";
pub const META_POCKETCASTS_COVER_ART_URL: &str = "POCKETCASTS_COVER_ART_URL";