dist: xenial
language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
addons:
    apt:
        packages:
            - gstreamer1.0
            - libasound2-dev
install: []
#    - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

script:
    - cargo build --verbose
    - cargo test --verbose
#    - wasm-pack build clients/http/wasm
