dist: xenial
language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
addons:
    apt:
        packages:
            - gstreamer1.0
            - libasound2-dev