dist: bionic
language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
addons:
    apt:
        packages:
            - libasound2-dev
            - libgstreamer1.0-dev
            - libgstreamer-plugins-base1.0-dev
            - libgstreamer-plugins-bad1.0-dev
            - libdbus-1-dev
            - dbus
install: []
#    - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

script:
    - cargo build --verbose
    - cargo test --verbose
#    - wasm-pack build clients/http/wasm
