[package]
name = "rustic-dbus-frontend"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
dbus = { git = "https://github.com/diwic/dbus-rs.git", features = ["futures"] }
dbus-tokio = { git = "https://github.com/diwic/dbus-rs.git" }
dbus-crossroads = { git = "https://github.com/diwic/dbus-rs.git" }
failure = "0.1"
tokio = { version = "0.2", features = ["rt-core"] }
log = "0.4"

[dependencies.rustic-api]
path = "../../core/api"
