[package]
name = "rustic-rodio-backend"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
license = "GPL-3.0"
edition = "2018"
readme = "README.md"
repository = "https://github.com/rustic-music-player/rustic"
homepage = "https://github.com/rustic-music-player/rustic"

[dependencies]
crossbeam-channel = "0.4"
log = "0.4"
failure = "0.1"
url = "2.1"
rodio = "0.11"
pinboard = "2"

[dependencies.rustic-core]
path = "../../core"
