[package]
name = "rustic-native-http-client"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
reqwest = { version = "0.10", features = ["json"] }
async-trait = "0.1"
rustic-http-client = { path = "../" }
rustic-api = { path = "../../../core/api" }
failure = "0.1"
log = "0.4"
url = "2.1"
#websocket = { version = "0.24", features = ["async", "async-ssl"] }

[dev-dependencies]
mockito = "0.25"
tokio = { version = "0.2", features = ["rt-threaded", "macros"] }
serde_json = "1"
