[package]
name = "rustic-core"
version = "0.1.0"
authors = ["Max Jööhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
reqwest = "0.9"
url = "1.7"
failure = "0.1"
md5 = "0.3.7"
image = "0.19"
crossbeam-channel = "0.2"
