pub const META_SOUNDCLOUD_USER_ID: &str = "SOUNDCLOUD_USER_ID";
pub const META_SOUNDCLOUD_TRACK_ID: &str = "SOUNDCLOUD_TRACK_ID";
pub const META_SOUNDCLOUD_STREAM_URL: &str = "SOUNDCLOUD_STREAM_URL";
pub const META_SOUNDCLOUD_COVER_ART_URL: &str = "SOUNDCLOUD_COVER_ART_URL";
