[package]
name = "rustic-local-provider"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
serde = "1.0"
serde_derive = "1.0"
log = "0.4"
walkdir = "2.1"
id3 = "0.3"
maplit = "1.0.1"
url = "2.1"
dirs = "2"
async-trait = "0.1"

[dependencies.rustic-core]
path = "../../core"
