[package]
name = "rustic-google-cast-backend"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
failure = "0.1"
mdns = "0.3"
rust_cast = "0.15.1"
crossbeam-channel = "0.5"
pinboard = "2.0.1"

[dependencies.rustic-core]
path = "../../core"
