[package]
name = "rustic-http-frontend"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/rustic-music-player/rustic"
homepage = "https://github.com/rustic-music-player/rustic"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
mime = "0.2.6"
actix = "0.8"
actix-web = "1"
actix-web-actors = "1.0.4"
actix-files = "0.1.7"
log = "0.4"
failure = "0.1"
futures = "0.1"
rayon = "1.0"
uuid = { version = "0.6", features = ["v4"] }
stopwatch = "0.0.7"
crossbeam-channel = "0.4"
base64 = "0.11"
itertools = "0.8"
urlencoding = { git = "https://github.com/bt/rust_urlencoding" }
serde_qs = { version = "0.5", features = ["actix"] }

[dependencies.rustic-core]
path = "../../core"
