[package]
name = "rustic-http-frontend"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/rustic-music-player/http-frontend"
homepage = "https://github.com/rustic-music-player/http-frontend"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
mime = "0.2.6"
slog = "2.1.1"
actix = "0.7"
actix-web = "0.7"
url = "1.7"
log = "0.4"
failure = "0.1"
rayon = "1.0"
uuid = { version = "0.6", features = ["v4"] }

[dependencies.rustic-core]
path = "../../core"
