[package]
name = "snapcast-api"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[features]
default = ["tcp", "http"]
tcp = []
http = ["surf"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
thiserror = "1"
surf = { version = "2.0.0-alpha.5", optional = true }
